import logging

letter_dict = {
	u'A': [
		':think1::iii::iii::think2:',
		':iii::nothing::nothing::iii:',
		':iii::iii::iii::iii:',
		':iii::nothing::nothing::iii:',
		':ink::nothing::nothing::ink:',
		':nothing::nothing::nothing::nothing:',
		':nothing::nothing::nothing::nothing:'],
	u'B': [
		':iii::iii::iii::think2:',
		':iii::nothing::nothing::iii:',
		':iii::iii::iii::iii:',
		':iii::nothing::nothing::iii:',
		':iii::iii::iii::thonkbow4:',
		':nothing::nothing::nothing::nothing:',
		':nothing::nothing::nothing::nothing:'],
	u'C': [
		':think1::iii::iii::thonkways:',
		':iii::nothing::nothing::nothing:',
		':iii::nothing::nothing::nothing:',
		':iii::nothing::nothing::nothing:',
		':thonkbow1::iii::iii::thonkways:',
		':nothing::nothing::nothing::nothing:',
		':nothing::nothing::nothing::nothing:'],
	u'D': [
		':iii::iii::iii::think2:',
		':iii::nothing::nothing::iii:',
		':iii::nothing::nothing::iii:',
		':iii::nothing::nothing::iii:',
		':iii::iii::iii::thonkbow4:',
		':nothing::nothing::nothing::nothing:',
		':nothing::nothing::nothing::nothing:'],
	u'E': [
		':think1::iii::iii::thonkways:',
		':iii::nothing::nothing::nothing:',
		':iii::iii::thonkways::nothing:',
		':iii::nothing::nothing::nothing:',
		':thonkbow1::iii::iii::thonkways:',
		':nothing::nothing::nothing::nothing:',
		':nothing::nothing::nothing::nothing:'],
	u'F': [
		':think1::iii::iii::thonkways:',
		':iii::nothing::nothing::nothing:',
		':iii::iii::thonkways::nothing:',
		':iii::nothing::nothing::nothing:',
		':ink::nothing::nothing::nothing:',
		':nothing::nothing::nothing::nothing:',
		':nothing::nothing::nothing::nothing:'],
	u'G': [
		':think1::iii::iii::think2:',
		':iii::nothing::nothing::ink:',
		':iii::nothing::think1::think2:',
		':iii::nothing::ink::iii:',
		':thonkbow1::iii::iii::thonkbow4:',
		':nothing::nothing::nothing::nothing:',
		':nothing::nothing::nothing::nothing:'],
	u'H': [
		':thi::nothing::nothing::thi:',
		':iii::nothing::nothing::iii:',
		':iii::iii::iii::iii:',
		':iii::nothing::nothing::iii:',
		':ink::nothing::nothing::ink:',
		':nothing::nothing::nothing::nothing:',
		':nothing::nothing::nothing::nothing:'],
	u'I': [
		':thinkways::iii::thonkways:',
		':nothing::iii::nothing:',
		':nothing::iii::nothing:',
		':nothing::iii::nothing:',
		':thinkways::iii::thonkways:',
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:'],
	u'J': [
		':thinkways::iii::iii::thonkways:',
		':nothing::nothing::iii::nothing:',
		':nothing::nothing::iii::nothing:',
		':thi::nothing::iii::nothing:',
		':thonkbow1::iii::thonkbow4::nothing:',
		':nothing::nothing::nothing::nothing:',
		':nothing::nothing::nothing::nothing:'],
	u'K': [
		':thi::nothing::nothing::thi:',
		':iii::think1::iii::thonkbow4:',
		':iii::iii::nothing::nothing:',
		':iii::thonkbow1::iii::think2:',
		':ink::nothing::nothing::ink:',
		':nothing::nothing::nothing::nothing:',
		':nothing::nothing::nothing::nothing:'],
	u'L': [
		':thi::nothing::nothing::nothing:',
		':iii::nothing::nothing::nothing:',
		':iii::nothing::nothing::nothing:',
		':iii::nothing::nothing::nothing:',
		':thonkbow1::iii::iii::thonkways:',
		':nothing::nothing::nothing::nothing:',
		':nothing::nothing::nothing::nothing:'],
	u'M': [
		':think1::iii::think2::think1::iii::think2:',
		':iii::nothing::iii::iii::nothing::iii:',
		':iii::nothing::iii::iii::nothing::iii:',
		':iii::nothing::iii::iii::nothing::iii:',
		':ink::nothing::think3::think4::nothing::ink:',
		':nothing::nothing::nothing::nothing::nothing::nothing:',
		':nothing::nothing::nothing::nothing::nothing::nothing:'],
	u'N': [
		':think1::think2::nothing::thi:',
		':iii::iii::nothing::iii:',
		':iii::thonkbow1::think2::iii:',
		':iii::nothing::iii::iii:',
		':ink::nothing::think3::think4:',
		':nothing::nothing::nothing::nothing:',
		':nothing::nothing::nothing::nothing:'],
	u'O': [
		':think1::iii::iii::think2:',
		':iii::nothing::nothing::iii:',
		':iii::nothing::nothing::iii:',
		':iii::nothing::nothing::iii:',
		':thonkbow1::iii::iii::thonkbow4:',
		':nothing::nothing::nothing::nothing:',
		':nothing::nothing::nothing::nothing:'],
	u'P': [
		':think1::iii::iii::think2:',
		':iii::nothing::nothing::iii:',
		':iii::iii::iii::thonkbow4:',
		':iii::nothing::nothing::nothing:',
		':ink::nothing::nothing::nothing:',
		':nothing::nothing::nothing::nothing:',
		':nothing::nothing::nothing::nothing:'],
	u'Q': [
		':think1::iii::iii::think2::nothing:',
		':iii::nothing::nothing::iii::nothing:',
		':iii::nothing::nothing::iii::nothing:',
		':iii::nothing::thi::iii::nothing:',
		':thonkbow1::iii::iii::iii::thonkways:',
		':nothing::nothing::nothing::nothing::nothing:',
		':nothing::nothing::nothing::nothing::nothing:'],
	u'R': [
		':iii::iii::iii::think2:',
		':iii::nothing::nothing::iii:',
		':iii::iii::iii::thonkbow4:',
		':iii::thonkbow1::iii::think2:',
		':ink::nothing::nothing::ink:',
		':nothing::nothing::nothing::nothing:',
		':nothing::nothing::nothing::nothing:'],
	u'S': [
		':think1::iii::iii::thonkways:',
		':iii::nothing::nothing::nothing:',
		':thonkbow1::iii::iii::think2:',
		':nothing::nothing::nothing::iii:',
		':thinkways::iii::iii::thonkbow4:',
		':nothing::nothing::nothing::nothing:',
		':nothing::nothing::nothing::nothing:'],
	u'T': [
		':thinkways::iii::thonkways:',
		':nothing::iii::nothing:',
		':nothing::iii::nothing:',
		':nothing::iii::nothing:',
		':nothing::ink::nothing:',
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:'],
	u'U': [
		':thi::nothing::nothing::thi:',
		':iii::nothing::nothing::iii:',
		':iii::nothing::nothing::iii:',
		':iii::nothing::nothing::iii:',
		':thonkbow1::iii::iii::thonkbow4:',
		':nothing::nothing::nothing::nothing:',
		':nothing::nothing::nothing::nothing:'],
	u'V': [
		':thi::nothing::nothing::thi:',
		':iii::nothing::nothing::iii:',
		':thonkbow1::think2::think1::thonkbow4:',
		':nothing::iii::iii::nothing:',
		':nothing::think3::think4::nothing:',
		':nothing::nothing::nothing::nothing:',
		':nothing::nothing::nothing::nothing:'],
	u'W': [
		':thi::nothing::nothing::nothing::nothing::thi:',
		':iii::nothing::think1::think2::nothing::iii:',
		':iii::nothing::iii::iii::nothing::iii:',
		':iii::nothing::iii::iii::nothing::iii:',
		':thonkbow1::iii::thonkbow4::thonkbow1::iii::thonkbow4:',
		':nothing::nothing::nothing::nothing::nothing::nothing:',
		':nothing::nothing::nothing::nothing::nothing::nothing:'],
	u'X': [
		':thi::nothing::nothing::thi:',
		':thonkbow1::think2::think1::thonkbow4:',
		':nothing::iii::iii::nothing:',
		':think1::thonkbow4::thonkbow1::think2:',
		':ink::nothing::nothing::ink:',
		':nothing::nothing::nothing::nothing:',
		':nothing::nothing::nothing::nothing:'],
	u'Y': [
		':thi::nothing::nothing::thi:',
		':thonkbow1::think2::think1::thonkbow4:',
		':nothing::iii::iii::nothing:',
		':nothing::iii::iii::nothing:',
		':nothing::think3::think4::nothing:',
		':nothing::nothing::nothing::nothing:',
		':nothing::nothing::nothing::nothing:'],
	u'Z': [
		':thinkways::iii::iii::iii:',
		':nothing::nothing::think1::thonkbow4:',
		':nothing::think1::thonkbow4::nothing:',
		':think1::thonkbow4::nothing::nothing:',
		':iii::iii::iii::thonkways:',
		':nothing::nothing::nothing::nothing:',
		':nothing::nothing::nothing::nothing:'],
	u'a': [
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:',
		':think1::iii::iii:',
		':iii::thonkwards::iii:',
		':thonkbow1::iii::iii:',
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:'],
	u'b': [
		':thi::nothing::nothing:',
		':iii::nothing::nothing:',
		':iii::iii::think2:',
		':iii::nothing::iii:',
		':thonkbow1::iii::thonkbow4:',
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:'],
	u'c': [
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:',
		':think1::iii::thonkways:',
		':iii::nothing::nothing:',
		':thonkbow1::iii::thonkways:',
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:'],
	u'd': [
		':nothing::nothing::thi:',
		':nothing::nothing::iii:',
		':think1::iii::iii:',
		':iii::nothing::iii:',
		':thonkbow1::iii::iii:',
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:'],
	u'e': [
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:',
		':think1::iii::think2:',
		':iii::iii::thonkbow4:',
		':thonkbow1::iii::thonkways:',
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:'],
	u'f': [
		':think1::thonkways:',
		':iii::nothing:',
		':iii::thonkways:',
		':iii::nothing:',
		':ink::nothing:',
		':nothing::nothing:',
		':nothing::nothing:'],
	u'g': [
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:',
		':think1::iii::think2:',
		':iii::nothing::iii:',
		':thonkbow1::iii::iii:',
		':nothing::nothing::iii:',
		':thinkways::iii::thonkbow4:'],
	u'h': [
		':thi::nothing::nothing:',
		':iii::nothing::nothing:',
		':iii::iii::think2:',
		':iii::nothing::iii:',
		':ink::nothing::ink:',
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:'],
	u'i': [
		':nothing:',
		':spin_thonk:',
		':thi:',
		':iii:',
		':ink:',
		':nothing:',
		':nothing:'],
	u'j': [
		':nothing::nothing:',
		':nothing::spin_thonk:',
		':nothing::thi:',
		':nothing::iii:',
		':nothing::iii:',
		':nothing::iii:',
		':thinkways::thonkbow4:'],
	u'k': [
		':thi::nothing::nothing:',
		':iii::nothing::thi:',
		':iii::iii::thonkbow4:',
		':iii::thonkbow1::think2:',
		':ink::nothing::ink:',
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:'],
	u'l': [
		':thi:',
		':iii:',
		':iii:',
		':iii:',
		':ink:',
		':nothing:',
		':nothing:'],
	u'm': [
		':nothing::nothing::nothing::nothing:',
		':nothing::nothing::nothing::nothing:',
		':think1::think2::think1::think2:',
		':iii::iii::iii::iii:',
		':ink::think3::think4::ink:',
		':nothing::nothing::nothing::nothing:',
		':nothing::nothing::nothing::nothing:'],
	u'n': [
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:',
		':iii::iii::think2:',
		':iii::nothing::iii:',
		':ink::nothing::ink:',
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:'],
	u'o': [
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:',
		':think1::iii::think2:',
		':iii::nothing::iii:',
		':thonkbow1::iii::thonkbow4:',
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:'],
	u'p': [
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:',
		':think1::iii::think2:',
		':iii::nothing::iii:',
		':iii::iii::thonkbow4:',
		':iii::nothing::nothing:',
		':ink::nothing::nothing:'],
	u'q': [
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:',
		':think1::iii::think2:',
		':iii::nothing::iii:',
		':thonkbow1::iii::iii:',
		':nothing::nothing::iii:',
		':nothing::nothing::ink:'],
	u'r': [
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:',
		':thi::think1::thonkways:',
		':iii::thonkbow4::nothing:',
		':ink::nothing::nothing:',
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:'],
	u's': [
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:',
		':think1::iii::thonkways:',
		':thonkbow1::iii::think2:',
		':thinkways::iii::thonkbow4:',
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:'],
	u't': [
		':nothing::nothing::nothing:',
		':nothing::thi::nothing:',
		':thinkways::iii::thonkways:',
		':nothing::iii::nothing:',
		':nothing::thonkbow1::thonkways:',
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:'],
	u'u': [
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:',
		':thi::nothing::thi:',
		':iii::nothing::iii:',
		':thonkbow1::iii::iii:',
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:'],
	u'v': [
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:',
		':thi::nothing::thi:',
		':iii::nothing::iii:',
		':thonkbow1::iii::thonkbow4:',
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:'],
	u'w': [
		':nothing::nothing::nothing::nothing:',
		':nothing::nothing::nothing::nothing:',
		':thi::think1::think2::thi:',
		':iii::iii::iii::iii:',
		':think3::think4::think3::think4:',
		':nothing::nothing::nothing::nothing:',
		':nothing::nothing::nothing::nothing:'],
	u'x': [
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:',
		':thinkways::think2::thi:',
		':think1::iii::thonkbow4:',
		':ink::thonkbow1::thonkways:',
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:'],
	u'y': [
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:',
		':thi::nothing::thi:',
		':iii::nothing::iii:',
		':thonkbow1::iii::iii:',
		':nothing::nothing::iii:',
		':thinkways::iii::thonkbow4:'],
	u'z': [
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:',
		':thinkways::iii::iii:',
		':think1::iii::thonkbow4:',
		':iii::iii::thonkways:',
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:'],
	u'\xdc': [
		':spin_thonk::nothing::nothing::spin_thonk:',
		':thi::nothing::nothing::thi:',
		':iii::nothing::nothing::iii:',
		':iii::nothing::nothing::iii:',
		':thonkbow1::iii::iii::thonkbow4:',
		':nothing::nothing::nothing::nothing:',
		':nothing::nothing::nothing::nothing:'],
	u'\xfc': [
		':nothing::nothing::nothing:',
		':spin_thonk::nothing::spin_thonk:',
		':thi::nothing::thi:',
		':iii::nothing::iii:',
		':thonkbow1::iii::iii:',
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:'],
	u'0': [
		':think1::iii::think2:',
		':iii::nothing::iii:',
		':iii::nothing::iii:',
		':iii::nothing::iii:',
		':thonkbow1::iii::thonkbow4:',
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:'],
	u'1': [
		':think1::iii::nothing:',
		':ink::iii::nothing:',
		':nothing::iii::nothing:',
		':nothing::iii::nothing:',
		':thinkways::iii::thonkways:',
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:'],
	u'2': [
		':think1::iii::think2:',
		':ink::nothing::iii:',
		':nothing::think1::thonkbow4:',
		':think1::thonkbow4::nothing:',
		':iii::iii::thonkways:',
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:'],
	u'3': [
		':think1::iii::think2:',
		':ink::nothing::iii:',
		':nothing::thinkways::iii:',
		':thi::nothing::iii:',
		':thonkbow1::iii::thonkbow4:',
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:'],
	u'4': [
		':thi::nothing::thi:',
		':iii::nothing::iii:',
		':thonkbow1::iii::iii:',
		':nothing::nothing::iii:',
		':nothing::nothing::ink:',
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:'],
	u'5': [
		':iii::iii::thonkways:',
		':iii::nothing::nothing:',
		':thonkbow1::iii::think2:',
		':thi::nothing::iii:',
		':thonkbow1::iii::thonkbow4:',
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:'],
	u'6': [
		':think1::iii::think2:',
		':iii::nothing::ink:',
		':iii::iii::think2:',
		':iii::thonkwards::iii:',
		':thonkbow1::iii::thonkbow4:',
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:'],
	u'7': [
		':thinkways::iii::think2:',
		':nothing::nothing::iii:',
		':nothing::think1::thonkbow4:',
		':think1::thonkbow4::nothing:',
		':ink::nothing::nothing:',
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:'],
	u'8': [
		':think1::iii::think2:',
		':iii::thonkwards::iii:',
		':iii::iii::iii:',
		':iii::thonkwards::iii:',
		':thonkbow1::iii::thonkbow4:',
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:'],
	u'9': [
		':think1::iii::think2:',
		':iii::thonkwards::iii:',
		':thonkbow1::iii::iii:',
		':thi::nothing::iii:',
		':thonkbow1::iii::thonkbow4:',
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:'],
	u'@': [
		':think1::iii::iii::iii::iii::iii::think2:',
		':iii::nothing::nothing::nothing::nothing::nothing::iii:',
		':iii::nothing::think1::iii::think2::nothing::iii:',
		':iii::nothing::iii::nothing::iii::nothing::iii:',
		':iii::nothing::thonkbow1::iii::iii::iii::thonkbow4:',
		':iii::nothing::nothing::nothing::nothing::nothing::nothing:',
		':thonkbow1::iii::iii::iii::iii::iii::thonkways:'],
	u'#': [
		':nothing::nothing::nothing::nothing::nothing:',
		':nothing::thi::nothing::thi::nothing:',
		':thinkways::iii::iii::iii::thonkways:',
		':nothing::iii::thonkwards::iii::nothing:',
		':thinkways::iii::iii::iii::thonkways:',
		':nothing::ink::nothing::ink::nothing:',
		':nothing::nothing::nothing::nothing::nothing:'],
	u'-': [
		':nothing::nothing:',
		':nothing::nothing:',
		':thinkways::thonkways:',
		':nothing::nothing:',
		':nothing::nothing:',
		':nothing::nothing:',
		':nothing::nothing:'],
	u'+': [
		':nothing::nothing::nothing:',
		':nothing::thi::nothing:',
		':thinkways::iii::thonkways:',
		':nothing::ink::nothing:',
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:'],
	u'*': [
		':nothing:',
		':nothing:',
		':eight_spoked_asterisk:',
		':nothing:',
		':nothing:',
		':nothing:',
		':nothing:'],
	u'=': [
		':nothing::nothing:',
		':thinkways::thonkways:',
		':nothing::nothing:',
		':thinkways::thonkways:',
		':nothing::nothing:',
		':nothing::nothing:',
		':nothing::nothing:'],
	u'_': [
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:',
		':thinkways::iii::thonkways:',
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:'],
	u'[': [
		':iii::thonkways:',
		':iii::nothing:',
		':iii::nothing:',
		':iii::nothing:',
		':iii::nothing:',
		':iii::thonkways:',
		':nothing::nothing:',],
	u']': [
		':thinkways::iii:',
		':nothing::iii:',
		':nothing::iii:',
		':nothing::iii:',
		':nothing::iii:',
		':thinkways::iii:',
		':nothing::nothing:',],
	u'{': [
		':nothing::iii::thonkways:',
		':nothing::iii::nothing:',
		':think1::thonkbow4::nothing:',
		':thonkbow1::think2::nothing:',
		':nothing::iii::nothing:',
		':nothing::iii::thonkways:',
		':nothing::nothing::nothing:',],
	u'}': [
		':thinkways::iii::nothing:',
		':nothing::iii::nothing:',
		':nothing::thonkbow1::think2:',
		':nothing::think1::thonkbow4:',
		':nothing::iii::nothing:',
		':thinkways::iii::nothing:',
		':nothing::nothing::nothing:',],
	u'(': [
		':think1::thonkways:',
		':iii::nothing:',
		':iii::nothing:',
		':iii::nothing:',
		':iii::nothing:',
		':thonkbow1::thonkways:',
		':nothing::nothing:',],
	u')': [
		':thinkways::think2:',
		':nothing::iii:',
		':nothing::iii:',
		':nothing::iii:',
		':nothing::iii:',
		':thinkways::thonkbow4:',
		':nothing::nothing:',],
	u'/': [
		':nothing::nothing::nothing::thi:',
		':nothing::nothing::think1::thonkbow4:',
		':nothing::think1::thonkbow4::nothing:',
		':think1::thonkbow4::nothing::nothing:',
		':ink::nothing::nothing::nothing:',
		':nothing::nothing::nothing::nothing:',
		':nothing::nothing::nothing::nothing:'],
	u'\\': [
		':thi::nothing::nothing::nothing:',
		':thonkbow1::think2::nothing::nothing:',
		':nothing::thonkbow1::think2::nothing:',
		':nothing::nothing::thonkbow1::think2:',
		':nothing::nothing::nothing::ink:',
		':nothing::nothing::nothing::nothing:',
		':nothing::nothing::nothing::nothing:'],
	u' ': [
		':nothing:',
		':nothing:',
		':nothing:',
		':nothing:',
		':nothing:',
		':nothing:',
		':nothing:'],
	u'\'': [
		':nothing:',
		':thi:',
		':ink:',
		':nothing:',
		':nothing:',
		':nothing:',
		':nothing:'],
	u'"': [
		':nothing:  :nothing:',
		':thi:  :thi:',
		':ink:  :ink:',
		':nothing:  :nothing:',
		':nothing:  :nothing:',
		':nothing:  :nothing:',
		':nothing:  :nothing:'],
	u',': [
		':nothing:',
		':nothing:',
		':nothing:',
		':nothing:',
		':thi:',
		':ink:',
		':nothing:'],
	u'.': [
		':nothing:',
		':nothing:',
		':nothing:',
		':nothing:',
		':spin_thonk:',
		':nothing:',
		':nothing:'],
	u':': [
		':nothing:',
		':nothing:',
		':spin_thonk:',
		':nothing:',
		':spin_thonk:',
		':nothing:',
		':nothing:'],
	u';': [
		':nothing:',
		':nothing:',
		':spin_thonk:',
		':nothing:',
		':thi:',
		':ink:',
		':nothing:'],
	u'!': [
		':thi:',
		':iii:',
		':iii:',
		':ink:',
		':spin_thonk:',
		':nothing:',
		':nothing:'],
	u'?': [
		':think1::iii::think2:',
		':ink::nothing::iii:',
		':nothing::think1::thonkbow4:',
		':nothing::ink::nothing:',
		':nothing::spin_thonk::nothing:',
		':nothing::nothing::nothing:',
		':nothing::nothing::nothing:'],
}


def thonkify(text):
	word_list = []
	for letter in text:
		logging.debug(letter)
		try:
			thonk_letter = letter_dict[letter]
			word_list.append(thonk_letter)
		except:
			logging.debug("Unable to get emoji for: %u", letter)
			pass
	prelim_final_word = [[], [], [], [], [], [], []]
	for letter in word_list:
		for i in range(7):
			prelim_final_word[i].append(letter[i])
	final_word = []
	for i in range(7):
		if len("".join(prelim_final_word[i]).replace(':nothing:','')) > 0:
			final_word.append(" ".join(prelim_final_word[i]))
	return "\n".join(final_word)