#!/bin/bash

APPCFG="$(which appcfg.py 2>/dev/null)"

if [[ ! -x "${APPCFG}" ]]; then
  APPCFG="${HOME}/google_appengine/appcfg.py"
fi
if [[ ! -x "${APPCFG}" ]]; then
  echo "Could not find appcfg.py" >&2
  exit 1
fi

exec "${APPCFG}" "$@"