#!/bin/bash

BASE="$(dirname "$(readlink -f "$0")")"
APPCFG="${BASE}/appcfg"
if [[ ! -x "${APPCFG}" ]]; then
  echo "Could not find appcfg at ${APPCFG}" >&2
  exit 1
fi

VERSION="${1}"
YAML="${VERSION}"

if [[ "${VERSION}" == "prod" ]]; then
  YAML=app
elif [[ "${VERSION}" == "staging" ]]; then
  YAML=app
elif [[ "${VERSION}" == "unstable" ]]; then
  YAML=dev
fi

"${APPCFG}" update_indexes "${BASE}/src"

"${APPCFG}" update "${BASE}/src/${YAML}.yaml" -V "${VERSION}" || exit 1

if [[ -e "${BASE}/build.properties.sh" ]]; then
  source "${BASE}/build.properties.sh"
  echo "Tagging build ${THONKIFY_SERVER_VERSION?} as deployed to ${VERSION}"
  git tag -afm "Deployed build ${THONKIFY_SERVER_VERSION?} to ${VERSION}" "${VERSION}" || exit 1
  git push -f origin "refs/tags/${VERSION}" || exit 1
  echo "Tagging complete."
fi