#!/bin/bash

BASE="$(dirname "$(readlink -f "$0")")"
APPCFG="${BASE}/appcfg"
if [[ ! -x "${APPCFG}" ]]; then
  echo "Could not find appcfg at ${APPCFG}" >&2
  exit 1
fi

VERSION="${1}"
YAML="${VERSION}"

if [[ "${VERSION}" == "prod" ]]; then
  YAML=app
elif [[ "${VERSION}" == "staging" ]]; then
  YAML=app
elif [[ "${VERSION}" == "unstable" ]]; then
  YAML=dev
fi

"${APPCFG}" update_indexes "${BASE}/src"